---
- hosts: all

  vars:
    applications:
      - alfred
      - dropbox
      - cord
      - iterm2
      - firefox
      - google-chrome
      - hipchat
      - phpstorm
      - mou
      - sequel-pro
      - spotify
      - the-unarchiver
      - transmit
      - viscosity
      - vagrant
      - virtualbox
      - vlc
      - sublime-text
      - skype
      - github
      - evernote
      - cloudapp
      - rescuetime
      - istat-menus
      - google-drive
      - chicken
    application_dir: /Applications
    brews:
      - ack
      - docker
      - hub
      - ios-webkit-debug-proxy
      - rsync
      - zsh
      - curl
      - ant
      - composer
      - git
      - ios-sim
      - htop-osx
      - tig
      - tree
      - wget
      - nmap
      - nodejs
      - npm
      - ansible
      - selenium
    caskroom_dir: /usr/local/caskroom
    dotfiles_dir: /Users/jcalonso/Projects/dotfiles
    email: EMAIL_HERE
    github_username: jcalonso
    home_dir: /Users/jcalonso
    name: Juan Carlos Alonso
    zsh_path: /usr/local/bin/zsh

  tasks:
    - include: tasks/homebrew.yml tags=homebrew
    - include: tasks/zsh.yml tags=zsh
    - include: tasks/dotfiles.yml tags=dotfiles
